name: Manual Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Establecer permisos para el token GITHUB_TOKEN
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Asegurarse de que se persisten las credenciales
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Crear una rama temporal para el despliegue
          git checkout --orphan gh-pages
          
          # Eliminar todos los archivos excepto la carpeta dist
          find . -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} \;
          
          # Mover el contenido de dist a la raíz
          mv dist/* .
          rm -rf dist
          
          # Agregar todos los archivos
          git add .
          
          # Commit de los cambios
          git commit -m "Deploy to GitHub Pages"
          
          # Usar el token de GitHub para autenticación
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          
          # Forzar el push a la rama gh-pages
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
